# Generated by Django 3.2.4 on 2021-06-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actus", "0002_savoir_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savoir",
            name="numero",
            field=models.CharField(max_length=3),
        ),
    ]
