# Generated by Django 3.2.4 on 2021-06-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actus", "0005_auto_20210629_2057"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savoir",
            name="disponible",
            field=models.BooleanField(null=True),
        ),
    ]
