# Generated by Django 3.2.4 on 2021-07-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actus', '0012_newsletter_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendasuivre',
            name='ville',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='agendasuivre',
            name='lieu',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
