# Generated by Django 3.2.4 on 2021-07-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actus', '0014_savoir_sous_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savoir',
            name='link_pdf',
            field=models.CharField(default='static/assets/pdf_savoir/', max_length=100),
        ),
    ]
