# Generated by Django 3.2.4 on 2021-07-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actus', '0015_alter_savoir_link_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savoir',
            name='link_pdf',
            field=models.CharField(blank=True, default='static/assets/pdf_savoir/', max_length=100),
        ),
    ]
