# Generated by Django 3.2.4 on 2021-07-05 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=5)),
                ('commune', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=10)),
                ('elu', models.BooleanField(default=False)),
                ('fonction_elu', models.CharField(blank=True, max_length=100)),
                ('total_don', models.IntegerField(default=0, null=True)),
                ('soutien', models.BooleanField(default=False)),
                ('campagne', models.BooleanField(default=False)),
                ('parrainage', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
